create table if not exists crmgenesis_responsecompany(
    ID INT (18) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	COMPANY_ID int(18) NOT NULL,
	DEAL_ID int(18) NOT NULL,
	STATUS_ID int(18) NOT NULL,
	UUID varchar(255),
	REDIRECT_URL varchar(255),
	RESPONSE_BODY longtext,
    DATE_CREATE DATETIME NULL,
    DATE_MODIFY DATETIME NULL,
    CREATED_BY_ID INT (18) UNSIGNED NOT NULL,
    MODIFY_BY_ID INT (18) UNSIGNED DEFAULT NULL
);
